version: '2'
services:
  build:
    build: 
      context : .
      dockerfile : build.dockerfile
    volumes:
      - ..:/app
  node:
    build: 
      context : .
      dockerfile : node.dockerfile
    entrypoint : bash -c " cd /app/dist && sleep 8 && supervisor --force-watch --inspect --restart-verbose app.js "  
    volumes:
      - ..:/app
    depends_on:
      - build  
    links:
      - "nats:nats" 
    environment:
      MS_NATS_URL : "nats://nats:4222"
      MS_EVENT_BUS_TYPE : "auto"
      MS_EVENT_BUS_TIMEOUT : 30000
      MS_HTTP : "true"
      MS_HTTP_PORT : 8080
      MS_HTTP_IP : "0.0.0.0"
      MS_HTTP_PREFIX : "/api/v1"
    ports:
      - "8080:8080"
      - "5858:5858"
      - "9229:9229"

  nats:
    image: nats 
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
