version: '2'
services:
  node:
    build: 
      context : .
      dockerfile : node.dockerfile
      args:
        INDEX: app.js
    networks:
      main:
        aliases : 
          - node
    volumes:
      - ../dist:/app
    environment:
      MS_NATS_URL : "nats://nats:4222"
      MS_EVENT_BUS_TYPE : "auto"
      MS_EVENT_BUS_TIMEOUT : 30000
      MS_HTTP : "true"
      MS_HTTP_PORT : 8080
      MS_HTTP_IP : "0.0.0.0"
      MS_HTTP_PREFIX : "/api/v1"
    ports:
      - "8080:8080"
      - "5858:5858"
      - "9229:9229"

  nats:
    image: nats
    networks:
      main:
        aliases : 
          - nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

networks:
   main: 